"""Verified CDC MMWR clinical guideline PDF catalog."""

GUIDELINES_PAGE_SIZE = 6

GUIDELINES_CATALOG = [
    {
        "code": "rr6702a1",
        "title": "Prevention of Pertussis, Tetanus, and Diphtheria with Vaccines in the United States: Recommendations of the Advisory Committee on Immunization Practices (ACIP)",
        "url": "https://www.cdc.gov/mmwr/volumes/67/rr/pdfs/rr6702a1-H.pdf",
        "filename": "rr6702a1.pdf",
        "description": "ACIP recommendations for pertussis, tetanus, and diphtheria vaccination in the United States.",
    },
    {
        "code": "rr6703a1",
        "title": "Prevention and Control of Seasonal Influenza with Vaccines: Recommendations of the Advisory Committee on Immunization Practices—United States, 2018–19 Influenza Season",
        "url": "https://www.cdc.gov/mmwr/volumes/67/rr/pdfs/rr6703a1-H.pdf",
        "filename": "rr6703a1.pdf",
        "description": "2018–19 seasonal influenza vaccine recommendations from ACIP.",
    },
    {
        "code": "rr6801a1",
        "title": "Dengue and Zika Virus Diagnostic Testing for Patients with a Clinically Compatible Illness and Risk for Infection with Both Viruses",
        "url": "https://www.cdc.gov/mmwr/volumes/68/rr/pdfs/rr6801a1-H.pdf",
        "filename": "rr6801a1.pdf",
        "description": "Guidance on diagnostic testing for dengue and Zika virus in clinically compatible patients.",
    },
    {
        "code": "rr6802a1",
        "title": "Japanese Encephalitis Vaccine: Recommendations of the Advisory Committee on Immunization Practices",
        "url": "https://www.cdc.gov/mmwr/volumes/68/rr/pdfs/rr6802a1-H.pdf",
        "filename": "rr6802a1.pdf",
        "description": "ACIP recommendations for Japanese encephalitis vaccination.",
    },
    {
        "code": "rr6804a1",
        "title": "Use of Anthrax Vaccine in the United States: Recommendations of the Advisory Committee on Immunization Practices, 2019",
        "url": "https://www.cdc.gov/mmwr/volumes/68/rr/pdfs/rr6804a1-H.pdf",
        "filename": "rr6804a1.pdf",
        "description": "ACIP recommendations for anthrax vaccine use in the United States.",
    },
    {
        "code": "rr6805a1",
        "title": "Recommendations for Providing Quality Sexually Transmitted Diseases Clinical Services, 2020",
        "url": "https://www.cdc.gov/mmwr/volumes/68/rr/pdfs/rr6805a1-H.pdf",
        "filename": "rr6805a1.pdf",
        "description": "Framework for delivering quality STD clinical services.",
    },
    {
        "code": "rr6901a1",
        "title": "Guidelines for the Treatment of Latent Tuberculosis Infection: Recommendations from the National Tuberculosis Controllers Association and CDC, 2020",
        "url": "https://www.cdc.gov/mmwr/volumes/69/rr/pdfs/rr6901a1-H.pdf",
        "filename": "rr6901a1.pdf",
        "description": "Preferred short-course regimens for latent tuberculosis infection treatment.",
    },
    {
        "code": "rr6902a1",
        "title": "CDC Recommendations for Hepatitis C Screening Among Adults — United States, 2020",
        "url": "https://www.cdc.gov/mmwr/volumes/69/rr/pdfs/rr6902a1-H.pdf",
        "filename": "rr6902a1.pdf",
        "description": "Universal hepatitis C screening recommendations for U.S. adults.",
    },
    {
        "code": "rr6903a1",
        "title": "Preexposure Prophylaxis for Prevention of HIV Acquisition Among Adolescents: Clinical Considerations, 2020",
        "url": "https://www.cdc.gov/mmwr/volumes/69/rr/pdfs/rr6903a1-H.pdf",
        "filename": "rr6903a1.pdf",
        "description": "Clinical considerations for HIV PrEP among adolescents.",
    },
    {
        "code": "rr6904a1",
        "title": "Assessing Solid Organ Donors and Monitoring Transplant Recipients for Human Immunodeficiency Virus, Hepatitis B Virus, and Hepatitis C Virus Infection — U.S. Public Health Service Guideline, 2020",
        "url": "https://www.cdc.gov/mmwr/volumes/69/rr/pdfs/rr6904a1-H.pdf",
        "filename": "rr6904a1.pdf",
        "description": "PHS guideline for donor assessment and transplant recipient monitoring.",
    },
    {
        "code": "rr6905a1",
        "title": "Prevention of Hepatitis A Virus Infection in the United States: Recommendations of the Advisory Committee on Immunization Practices, 2020",
        "url": "https://www.cdc.gov/mmwr/volumes/69/rr/pdfs/rr6905a1-H.pdf",
        "filename": "rr6905a1.pdf",
        "description": "ACIP recommendations for hepatitis A prevention and vaccination.",
    },
    {
        "code": "rr6906a1",
        "title": "Testing and Clinical Management of Health Care Personnel Potentially Exposed to Hepatitis C Virus — CDC Guidance, United States, 2020",
        "url": "https://www.cdc.gov/mmwr/volumes/69/rr/pdfs/rr6906a1-H.pdf",
        "filename": "rr6906a1.pdf",
        "description": "CDC guidance for HCV exposure management among health care personnel.",
    },
    {
        "code": "rr6907a1",
        "title": "Essential Components of a Public Health Tuberculosis Prevention, Control, and Elimination Program: Recommendations of the Advisory Council for the Elimination of Tuberculosis and the National Tuberculosis Controllers Association",
        "url": "https://www.cdc.gov/mmwr/volumes/69/rr/pdfs/rr6907a1-H.pdf",
        "filename": "rr6907a1.pdf",
        "description": "Core components of effective public health tuberculosis programs.",
    },
    {
        "code": "rr6908a1",
        "title": "Prevention and Control of Seasonal Influenza with Vaccines: Recommendations of the Advisory Committee on Immunization Practices — United States, 2020–21 Influenza Season",
        "url": "https://www.cdc.gov/mmwr/volumes/69/rr/pdfs/rr6908a1-H.pdf",
        "filename": "rr6908a1.pdf",
        "description": "2020–21 seasonal influenza vaccine recommendations from ACIP.",
    },
    {
        "code": "rr6909a1",
        "title": "Meningococcal Vaccination: Recommendations of the Advisory Committee on Immunization Practices, United States, 2020",
        "url": "https://www.cdc.gov/mmwr/volumes/69/rr/pdfs/rr6909a1-H.pdf",
        "filename": "rr6909a1.pdf",
        "description": "ACIP meningococcal vaccination recommendations for the United States.",
    },
    {
        "code": "rr7001a1",
        "title": "Use of Ebola Vaccine: Recommendations of the Advisory Committee on Immunization Practices, United States, 2020",
        "url": "https://www.cdc.gov/mmwr/volumes/70/rr/pdfs/rr7001a1-H.pdf",
        "filename": "rr7001a1.pdf",
        "description": "ACIP recommendations for Ebola vaccine use in the United States.",
    },
    {
        "code": "rr7002a1",
        "title": "Clinical Guidelines for Diagnosis and Treatment of Botulism, 2021",
        "url": "https://www.cdc.gov/mmwr/volumes/70/rr/pdfs/rr7002a1-H.pdf",
        "filename": "rr7002a1.pdf",
        "description": "Clinical guidance for diagnosing and treating botulism.",
    },
    {
        "code": "rr7003a1",
        "title": "Antimicrobial Treatment and Prophylaxis of Plague: Recommendations for Naturally Acquired Infections and Bioterrorism Response",
        "url": "https://www.cdc.gov/mmwr/volumes/70/rr/pdfs/rr7003a1-H.pdf",
        "filename": "rr7003a1.pdf",
        "description": "Antimicrobial treatment and prophylaxis recommendations for plague.",
    },
    {
        "code": "rr7004a1",
        "title": "Sexually Transmitted Infections Treatment Guidelines, 2021",
        "url": "https://www.cdc.gov/mmwr/volumes/70/rr/pdfs/rr7004a1-H.pdf",
        "filename": "rr7004a1.pdf",
        "description": "Comprehensive CDC treatment guidelines for sexually transmitted infections.",
    },
    {
        "code": "rr7005a1",
        "title": "Prevention and Control of Seasonal Influenza with Vaccines: Recommendations of the Advisory Committee on Immunization Practices, United States, 2021–22 Influenza Season",
        "url": "https://www.cdc.gov/mmwr/volumes/70/rr/pdfs/rr7005a1-H.pdf",
        "filename": "rr7005a1.pdf",
        "description": "2021–22 seasonal influenza vaccine recommendations from ACIP.",
    },
    {
        "code": "rr7006a1",
        "title": "Dengue Vaccine: Recommendations of the Advisory Committee on Immunization Practices, United States, 2021",
        "url": "https://www.cdc.gov/mmwr/volumes/70/rr/pdfs/rr7006a1-H.pdf",
        "filename": "rr7006a1.pdf",
        "description": "ACIP recommendations for dengue vaccination in the United States.",
    },
    {
        "code": "rr7101a1",
        "title": "Prevention and Control of Seasonal Influenza with Vaccines: Recommendations of the Advisory Committee on Immunization Practices — United States, 2022–23 Influenza Season",
        "url": "https://www.cdc.gov/mmwr/volumes/71/rr/pdfs/rr7101a1-H.pdf",
        "filename": "rr7101a1.pdf",
        "description": "2022–23 seasonal influenza vaccine recommendations from ACIP.",
    },
    {
        "code": "rr7102a1",
        "title": "Cholera Vaccine: Recommendations of the Advisory Committee on Immunization Practices, 2022",
        "url": "https://www.cdc.gov/mmwr/volumes/71/rr/pdfs/rr7102a1-H.pdf",
        "filename": "rr7102a1.pdf",
        "description": "ACIP recommendations for cholera vaccination.",
    },
    {
        "code": "rr7103a1",
        "title": "CDC Clinical Practice Guideline for Prescribing Opioids for Pain — United States, 2022",
        "url": "https://www.cdc.gov/mmwr/volumes/71/rr/pdfs/rr7103a1-H.pdf",
        "filename": "rr7103a1.pdf",
        "description": "Twelve practice recommendations for opioid prescribing in chronic and acute pain.",
    },
    {
        "code": "rr7104a1",
        "title": "Council of State and Territorial Epidemiologists/CDC Surveillance Case Definition for Multisystem Inflammatory Syndrome in Children Associated with SARS-CoV-2 Infection — United States",
        "url": "https://www.cdc.gov/mmwr/volumes/71/rr/pdfs/rr7104a1-H.pdf",
        "filename": "rr7104a1.pdf",
        "description": "Surveillance case definition for MIS-C associated with SARS-CoV-2 infection.",
    },
    {
        "code": "rr7201a1",
        "title": "Screening and Testing for Hepatitis B Virus Infection: CDC Recommendations — United States, 2023",
        "url": "https://www.cdc.gov/mmwr/volumes/72/rr/pdfs/rr7201a1-H.pdf",
        "filename": "rr7201a1.pdf",
        "description": "CDC recommendations for hepatitis B screening and testing among adults.",
    },
    {
        "code": "rr7202a1",
        "title": "Prevention and Control of Seasonal Influenza with Vaccines: Recommendations of the Advisory Committee on Immunization Practices — United States, 2023–24 Influenza Season",
        "url": "https://www.cdc.gov/mmwr/volumes/72/rr/pdfs/rr7202a1-H.pdf",
        "filename": "rr7202a1.pdf",
        "description": "2023–24 seasonal influenza vaccine recommendations from ACIP.",
    },
    {
        "code": "rr7203a1",
        "title": "Pneumococcal Vaccine for Adults Aged ≥19 Years: Recommendations of the Advisory Committee on Immunization Practices, United States, 2023",
        "url": "https://www.cdc.gov/mmwr/volumes/72/rr/pdfs/rr7203a1-H.pdf",
        "filename": "rr7203a1.pdf",
        "description": "Updated ACIP pneumococcal vaccination recommendations for U.S. adults.",
    },
    {
        "code": "rr7204a1",
        "title": "CDC Recommendations for Hepatitis C Testing Among Perinatally Exposed Infants and Children — United States, 2023",
        "url": "https://www.cdc.gov/mmwr/volumes/72/rr/pdfs/rr7204a1-H.pdf",
        "filename": "rr7204a1.pdf",
        "description": "Hepatitis C testing recommendations for perinatally exposed infants and children.",
    },
    {
        "code": "rr7205a1",
        "title": "Tick-Borne Encephalitis Vaccine: Recommendations of the Advisory Committee on Immunization Practices, United States, 2023",
        "url": "https://www.cdc.gov/mmwr/volumes/72/rr/pdfs/rr7205a1-H.pdf",
        "filename": "rr7205a1.pdf",
        "description": "ACIP recommendations for tick-borne encephalitis vaccination.",
    },
    {
        "code": "rr7206a1",
        "title": "CDC Guidelines for the Prevention and Treatment of Anthrax, 2023",
        "url": "https://www.cdc.gov/mmwr/volumes/72/rr/pdfs/rr7206a1-H.pdf",
        "filename": "rr7206a1.pdf",
        "description": "Comprehensive CDC guidance for anthrax prevention and treatment.",
    },
    {
        "code": "rr7301a1",
        "title": "CDC Laboratory Recommendations for Syphilis Testing, United States, 2024",
        "url": "https://www.cdc.gov/mmwr/volumes/73/rr/pdfs/rr7301a1-H.pdf",
        "filename": "rr7301a1.pdf",
        "description": "Laboratory testing algorithm recommendations for syphilis diagnosis.",
    },
    {
        "code": "rr7302a1",
        "title": "CDC Clinical Guidelines on the Use of Doxycycline Postexposure Prophylaxis for Bacterial Sexually Transmitted Infection Prevention, United States, 2024",
        "url": "https://www.cdc.gov/mmwr/volumes/73/rr/pdfs/rr7302a1-H.pdf",
        "filename": "rr7302a1.pdf",
        "description": "Clinical guidance for doxycycline postexposure prophylaxis (Doxy-PEP).",
    },
    {
        "code": "rr7303a1",
        "title": "U.S. Selected Practice Recommendations for Contraceptive Use, 2024",
        "url": "https://www.cdc.gov/mmwr/volumes/73/rr/pdfs/rr7303a1-H.pdf",
        "filename": "rr7303a1.pdf",
        "description": "Selected practice recommendations for contraceptive use in the United States.",
    },
    {
        "code": "rr7304a1",
        "title": "U.S. Medical Eligibility Criteria for Contraceptive Use, 2024",
        "url": "https://www.cdc.gov/mmwr/volumes/73/rr/pdfs/rr7304a1-H.pdf",
        "filename": "rr7304a1.pdf",
        "description": "Medical eligibility criteria for contraceptive use in the United States.",
    },
    {
        "code": "rr7305a1",
        "title": "Prevention and Control of Seasonal Influenza with Vaccines: Recommendations of the Advisory Committee on Immunization Practices — United States, 2024–25 Influenza Season",
        "url": "https://www.cdc.gov/mmwr/volumes/73/rr/pdfs/rr7305a1-H.pdf",
        "filename": "rr7305a1.pdf",
        "description": "2024–25 seasonal influenza vaccine recommendations from ACIP.",
    },
    {
        "code": "rr7306a1",
        "title": "CDC Program Evaluation Framework, 2024",
        "url": "https://www.cdc.gov/mmwr/volumes/73/rr/pdfs/rr7306a1-H.pdf",
        "filename": "rr7306a1.pdf",
        "description": "Updated CDC framework for planning and implementing program evaluation.",
    },
    {
        "code": "rr7401a1",
        "title": "Antiretroviral Postexposure Prophylaxis After Sexual, Injection Drug Use, or Other Nonoccupational Exposure to HIV — CDC Recommendations, United States, 2025",
        "url": "https://www.cdc.gov/mmwr/volumes/74/rr/pdfs/rr7401a1-H.pdf",
        "filename": "rr7401a1.pdf",
        "description": "Updated nPEP recommendations after nonoccupational HIV exposure.",
    },
    {
        "code": "rr7402a1",
        "title": "Tularemia Antimicrobial Treatment and Prophylaxis: CDC Recommendations for Naturally Acquired Infections and Bioterrorism Response — United States, 2025",
        "url": "https://www.cdc.gov/mmwr/volumes/74/rr/pdfs/rr7402a1-H.pdf",
        "filename": "rr7402a1.pdf",
        "description": "Antimicrobial treatment and prophylaxis recommendations for tularemia.",
    },
]

DEFAULT_GUIDELINES = {
    item["title"]: {
        "url": item["url"],
        "filename": item["filename"],
        "description": item["description"],
        "code": item["code"],
    }
    for item in GUIDELINES_CATALOG
}

GUIDELINE_BY_CODE = {item["code"]: item for item in GUIDELINES_CATALOG}
